version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.1
    - 2.32.10
    - 2.32.11
    - 2.32.12
    - 2.32.2
    - 2.32.3
    - 2.32.4
    - 2.32.6
    - 2.32.8
    - 2.32.9
    - 3.2.1
  - dependency-name: gatsby-image
    versions:
    - 2.11.0
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.10.0
    - 2.11.0
    - 2.11.1
    - 3.2.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.12.0
    - 2.12.1
    - 3.0.0
    - 3.1.0
    - 3.2.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.10.0
    - 3.9.0
    - 4.0.0
    - 4.2.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.14.1
    - 2.14.2
    - 2.14.3
    - 3.0.1
  - dependency-name: gatsby-plugin-google-analytics
    versions:
    - 2.11.0
    - 3.0.0
  - dependency-name: react-dom
    versions:
    - 16.14.0
    - 17.0.1
  - dependency-name: react-headroom
    versions:
    - 3.1.0
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: gatsby-plugin-netlify
    versions:
    - 2.10.0
    - 2.11.0
  - dependency-name: gatsby-remark-images
    versions:
    - 3.10.0
    - 3.11.0
  - dependency-name: gatsby-plugin-remove-trailing-slashes
    versions:
    - 2.9.0
  - dependency-name: gatsby-transformer-remark
    versions:
    - 2.15.0
  - dependency-name: gatsby-transformer-yaml
    versions:
    - 2.10.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
