---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: document
  path: content/pages/info.md
  label: Info Page
- type: directory
  path: content/text
  label: Text
  create: documents
  match: "**/*"
  templates:
  - text-upload
  - text
- type: directory
  path: content/exhibitions
  label: Exhibitions
  create: documents
  match: "**/*"
  templates:
  - exhibition
upload_dir: content/assets
public_path: "/content/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: gatsby develop -H 0.0.0.0 -p 8080
  publish_command: gatsby build
  output_directory: public
  preview_command: gatsby build
