---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/text
  label: Text
  create: documents
  match: "**/*"
- type: directory
  path: content/exhibitions
  label: Exhibitions
  create: documents
  match: "**/*"
upload_dir: content/assets
public_path: "/content/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: gatsby build
  publish_command: gatsby build
  preview_output_directory: public
  output_directory: public
